scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

